name: A workflow for my Hello World file
on: [issues, pull_request]
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: lindell/label-commenter@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            not reproducible:
              text: |
                Hi and thanks for creating this issue.
                Unfortunately, the information you have provided is not enough to reproduce the error you have stated.
                Please provide more information and this issue will hopefully be solved.
              ignore-previous: true
